### ISSUE TITLE
add_popup also for Bar charts?

### ISSUE THREAD

**Issue by altsheets** [jaraco/svg.charts#11]
When trying
 
    g.add_popups=True
    g.add_popup(2, 36000, "test")

with a VerticalBar, I get these errors:

     Traceback (most recent call last):
       File "svgcharts_test.py", line 173, in <module>
         g.add_popup(2, 36000, "test")
       File "lib\site-packages\svg\charts\graph.py", line 244, in add_popup
         etree.SubElement(self.foreground, 'text', {
     AttributeError: 'VerticalBar' object has no attribute 'foreground'

Sorry for all these little questions. But most of them are suggestions, with ready code - and easy to solve. This one however might not. But it would be cool to be able to hover over a Bar chart rect and get a lot of additional information, preferably multi-line text possible.

Thanks by the way. 

A superb library. I really like all the options it is giving me. 

Bigbig Kudos for this!

**Comment by jaraco** [comment]
Looks like `add_popups` isn't used anywhere, so I've removed it to avoid confusion. But for `add_popup`, I agree it should be possible to use that elsewhere. Currently, it's only used in `svg.charts.plot`.

**Comment by jaraco** [comment]
I note that the reason `add_popup` isn't working for you is because you're calling it before `self.foreground` is set, and `self.foreground` is set in `Graph.burn`. If you attempt to call `self.add_popup` in a DrawHook, it should work.

I also note that `add_popup` is meant for adding detail to a point on a plot, and isn't suited for what you're trying (responding to a box instead of a point). However, I could see you adapting the technique in `Graph.add_popup` to create a new method in `Bar.add_popup`, which takes the bar dimensions and creates just what you're describing, detail about that aspect of the data.

I won't have the time to implement this, but I'll be happy to answer questions if you get stuck implementing it for yourself. And if you have something that looks like it will have general-purpose use, I'll be happy to incorporate it.

**Comment by altsheets** [comment]
Cool. 

>  to create a new method in ``Bar.add_popup`` 
>  ... implementing it for yourself

Yes. I might consider that, at some later stage. 

For now, I have simply put all extra information into some `` xlink:title=`` - and the user will see that when he is hovering over my footnote link.

I guess ``popup`` is not so much different from that?

Thanks!

**Comment by jaraco** [comment]
Sounds good to me.
