### ISSUE TITLE
help Eclipse to find the sources

### ISSUE THREAD

**Issue by altsheets** [jaraco/svg.charts#7]
Eclipse Pydev was not able to find, and navigate into your sourcecode. It did run, but in the editor there were red "unresolved import ..." everywhere.

It was easy to fix.   

I just had to put an (even empty) 

    svg/__init__.py

so besides 

    charts

and tell Eclipse to rescan the PYTHONPATH for the default interpreter.

P.S.: I had been using the version that got installed with

    pip install svg.charts

**Comment by jaraco** [comment]
The [file exists](https://github.com/jaraco/svg.charts/blob/master/svg/__init__.py) in the source code. The issue is that pip removes the file as it relies instead on the package metadata to locate and resolve "namespace packages", of which `svg` is one such package.

Therefore, I don't think there's anything that this project can do to help. Your best bet is to file a feature request with Pydev, or just to rely on the workaround you've devised.

**Comment by altsheets** [comment]
I have tweeted the author of https://github.com/fabioz/Pydev (as issues are switched off there).

Thx a lot.
